import { create } from 'zustand';

// Define interfaces for better type safety
interface OrderItem {
  id: string;
  inventory_item_id: string;
  quantity: number;
  unit_price: number;
  total_price: number;
  inventory_items: { name: string };
}

interface Order {
  id: string;
  order_number: string;
  supplier_id: string;
  suppliers: { name: string };
  status: string;
  total_amount: number;
  expected_delivery_date: string | null;
  notes: string;
  created_at: string;
  updated_at: string;
  order_items: OrderItem[];
  isAutoGenerated?: boolean;
  autoOrderReason?: string;
}

interface OrderStore {
  orders: Order[];
  addOrder: (order: Order) => void;
  updateOrder: (orderId: string, updates: Partial<Order>) => void;
  setOrders: (orders: Order[]) => void;
  getOrderById: (id: string) => Order | undefined;
}

// Initial hardcoded orders data
const initialOrders: Order[] = [
  {
    id: "1",
    order_number: "PO-2024-001",
    supplier_id: "1",
    suppliers: { name: "VASUMATHI ELECTRONIC" },
    status: "pending",
    total_amount: 6750.00,
    expected_delivery_date: "2024-01-20",
    notes: "Urgent order for electrical components",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-01-15T10:30:00Z",
    order_items: [
      {
        id: "1",
        inventory_item_id: "1",
        quantity: 10,
        unit_price: 450.00,
        total_price: 4500.00,
        inventory_items: { name: "Circuit Breaker 32A" }
      },
      {
        id: "2",
        inventory_item_id: "2",
        quantity: 15,
        unit_price: 150.00,
        total_price: 2250.00,
        inventory_items: { name: "Electrical Switch 16A" }
      }
    ]
  },
  {
    id: "2",
    order_number: "PO-2024-002",
    supplier_id: "2",
    suppliers: { name: "TechParts Supply Co." },
    status: "in_transit",
    total_amount: 6600.00,
    expected_delivery_date: "2024-01-18",
    notes: "Automotive parts for service center",
    created_at: "2024-01-12T14:15:00Z",
    updated_at: "2024-01-16T09:20:00Z",
    order_items: [
      {
        id: "3",
        inventory_item_id: "3",
        quantity: 3,
        unit_price: 2200.00,
        total_price: 6600.00,
        inventory_items: { name: "Brake Pad Set" }
      }
    ]
  },
  {
    id: "3",
    order_number: "PO-2024-003",
    supplier_id: "3",
    suppliers: { name: "Global Components Ltd." },
    status: "delivered",
    total_amount: 12750.00,
    expected_delivery_date: "2024-01-10",
    notes: "Bulk cable order for new project",
    created_at: "2024-01-08T16:45:00Z",
    updated_at: "2024-01-11T11:30:00Z",
    order_items: [
      {
        id: "4",
        inventory_item_id: "4",
        quantity: 150,
        unit_price: 85.00,
        total_price: 12750.00,
        inventory_items: { name: "Power Cable 2.5 sqmm" }
      }
    ]
  },
  {
    id: "4",
    order_number: "PO-2024-004",
    supplier_id: "1",
    suppliers: { name: "VASUMATHI ELECTRONIC" },
    status: "cancelled",
    total_amount: 3500.00,
    expected_delivery_date: "2024-01-25",
    notes: "Order cancelled due to specification changes",
    created_at: "2024-01-20T08:00:00Z",
    updated_at: "2024-01-22T14:15:00Z",
    order_items: [
      {
        id: "5",
        inventory_item_id: "5",
        quantity: 100,
        unit_price: 35.00,
        total_price: 3500.00,
        inventory_items: { name: "Copper Wire 1.0 sqmm" }
      }
    ]
  }
];

export const useOrderStore = create<OrderStore>((set, get) => ({
  orders: initialOrders,
  
  addOrder: (order) => 
    set((state) => ({ 
      orders: [order, ...state.orders] 
    })),
  
  updateOrder: (orderId, updates) =>
    set((state) => ({
      orders: state.orders.map(order =>
        order.id === orderId ? { ...order, ...updates } : order
      )
    })),
  
  setOrders: (orders) => set({ orders }),
  
  getOrderById: (id) => get().orders.find(order => order.id === id),
}));

export type { Order, OrderItem };