import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useOrderStore } from "@/lib/orderStore";
import { Clock, ShoppingCart, TrendingUp, CheckCircle } from "lucide-react";

const AutoOrderStatus = () => {
  const { orders } = useOrderStore();
  const [autoOrdersCount, setAutoOrdersCount] = useState(0);
  const [lastOrderTime, setLastOrderTime] = useState<Date | null>(null);

  // Filter auto-generated orders
  const autoOrders = orders.filter(order => order.isAutoGenerated);
  
  useEffect(() => {
    setAutoOrdersCount(autoOrders.length);
    if (autoOrders.length > 0) {
      const latestOrder = autoOrders[0];
      setLastOrderTime(new Date(latestOrder.created_at));
    }
  }, [autoOrders.length]);

  const totalAutoOrderValue = autoOrders.reduce((sum, order) => sum + order.total_amount, 0);
  
  return (
    <div className="grid gap-4 md:grid-cols-4">
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <ShoppingCart className="h-4 w-4 text-primary" />
            Auto Orders Today
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{autoOrdersCount}</div>
          <div className="flex items-center gap-2 mt-1">
            <Badge variant="default" className="text-xs">
              Active
            </Badge>
            <span className="text-xs text-muted-foreground">Generated automatically</span>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-success" />
            Total Value
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">₹{totalAutoOrderValue.toLocaleString()}</div>
          <p className="text-xs text-muted-foreground mt-1">Auto-generated orders</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <Clock className="h-4 w-4 text-info" />
            Last Order
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-lg font-bold">
            {lastOrderTime ? lastOrderTime.toLocaleTimeString() : "No orders"}
          </div>
          <p className="text-xs text-muted-foreground mt-1">
            {lastOrderTime ? `${Math.floor((new Date().getTime() - lastOrderTime.getTime()) / 1000 / 60)} min ago` : "Waiting for first order"}
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <CheckCircle className="h-4 w-4 text-success" />
            System Status
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-lg font-bold text-success">Active</div>
          <p className="text-xs text-muted-foreground mt-1">Generating orders every minute</p>
        </CardContent>
      </Card>
    </div>
  );
};

export default AutoOrderStatus;