import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { useOrderStore, Order } from "@/lib/orderStore";
import { 
  Zap, 
  ShoppingCart, 
  Clock, 
  Settings, 
  AlertTriangle, 
  CheckCircle,
  Package,
  Calendar
} from "lucide-react";

interface AutoOrderManagerProps {
  inventoryItems: any[];
  suppliers: any[];
}

const AutoOrderManager = ({ inventoryItems = [], suppliers = [] }: AutoOrderManagerProps) => {
  // Debug: log incoming props to detect undefined or unexpected shapes
  // This helps confirm the parent is passing the correct data.
  // Remove or reduce verbosity in production.
  // eslint-disable-next-line no-console
  console.log("AutoOrderManager inventoryItems:", inventoryItems);
  const { addOrder } = useOrderStore();
  const [autoOrderEnabled, setAutoOrderEnabled] = useState(true);
  const [reorderSettings, setReorderSettings] = useState({
    safetyStockMultiplier: 1.5,
    leadTimeBuffer: 2,
    minOrderAmount: 1000,
    autoApproveThreshold: 5000,
  });
  const [scheduledOrders, setScheduledOrders] = useState<any[]>([]);
  const [autoOrderHistory, setAutoOrderHistory] = useState<any[]>([]);

  // Check for items that need automatic reordering
  const checkLowStockItems = () => {
    return inventoryItems.filter(item => {
      const reorderPoint = item.reorder_point * reorderSettings.safetyStockMultiplier;
      return item.current_quantity <= reorderPoint;
    });
  };

  // Calculate optimal reorder quantity
  const calculateReorderQuantity = (item: any) => {
    const leadTime = item.suppliers?.average_delivery_days || 7;
    const dailyDemand = item.optimal_quantity / 30; // Simplified daily demand
    const safetyStock = item.reorder_point * reorderSettings.safetyStockMultiplier;
    const leadTimeDemand = dailyDemand * (leadTime + reorderSettings.leadTimeBuffer);
    
    return Math.ceil(Math.max(
      item.optimal_quantity - item.current_quantity + safetyStock,
      leadTimeDemand
    ));
  };

  // Create automatic order
  const createAutoOrder = (items: any[]) => {
    if (items.length === 0) return;

    // Group items by supplier
    const ordersBySupplier: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const supplierId = item.supplier_id || "1"; // Default to first supplier
      if (!ordersBySupplier[supplierId]) {
        ordersBySupplier[supplierId] = [];
      }
      ordersBySupplier[supplierId].push({
        ...item,
        reorderQuantity: calculateReorderQuantity(item)
      });
    });

    // Create orders for each supplier
    Object.entries(ordersBySupplier).forEach(([supplierId, supplierItems]) => {
      const supplier = suppliers.find(s => s.id === supplierId);
      if (!supplier) return;

      const totalAmount = supplierItems.reduce((sum, item) => 
        sum + (item.reorderQuantity * item.unit_cost), 0
      );

      const newOrder: Order = {
        id: `auto-${Date.now()}-${supplierId}`,
        order_number: `AUTO-${new Date().getFullYear()}-${String(autoOrderHistory.length + 1).padStart(3, '0')}`,
        supplier_id: supplierId,
        suppliers: { name: supplier.name },
        status: totalAmount <= reorderSettings.autoApproveThreshold ? "pending" : "draft",
        total_amount: totalAmount,
        expected_delivery_date: new Date(Date.now() + (supplier.average_delivery_days * 24 * 60 * 60 * 1000)).toISOString().split('T')[0],
        notes: `Automatic reorder - Low stock alert`,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        order_items: supplierItems.map(item => ({
          id: `${item.id}-${Date.now()}`,
          inventory_item_id: item.id,
          quantity: item.reorderQuantity,
          unit_price: item.unit_cost,
          total_price: item.reorderQuantity * item.unit_cost,
          inventory_items: { name: item.name }
        })),
        isAutoGenerated: true,
        autoOrderReason: "Low stock reorder"
      };

      addOrder(newOrder);
      
      // Add to auto order history
      setAutoOrderHistory(prev => [newOrder, ...prev.slice(0, 9)]); // Keep last 10
      
      toast.success(`Auto order created for ${supplier.name} - ₹${totalAmount.toLocaleString()}`);
    });
  };

  // Schedule daily check for automatic orders
  useEffect(() => {
    if (!autoOrderEnabled) return;

    const checkInterval = setInterval(() => {
      const lowStockItems = checkLowStockItems();
      if (lowStockItems.length > 0) {
        createAutoOrder(lowStockItems);
      }
    }, 60000); // Check every 60 seconds (1 minute)

    return () => clearInterval(checkInterval);
  }, [autoOrderEnabled, inventoryItems, suppliers, reorderSettings]);

  // Manual trigger for automatic orders
  const handleManualAutoOrder = () => {
    const lowStockItems = checkLowStockItems();
    if (lowStockItems.length === 0) {
      toast.info("No items need automatic reordering at this time");
      return;
    }
    createAutoOrder(lowStockItems);
  };

  const lowStockItems = checkLowStockItems();
  const pendingAutoOrders = autoOrderHistory.filter(order => order.status === "draft");

  return (
    <div className="space-y-6">
      {/* Auto Order Settings */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-primary" />
            Automatic Order Management
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <Label htmlFor="auto-order">Enable Automatic Reordering</Label>
              <p className="text-sm text-muted-foreground">
                Automatically create orders when items reach low stock levels
              </p>
            </div>
            <Switch
              id="auto-order"
              checked={autoOrderEnabled}
              onCheckedChange={setAutoOrderEnabled}
            />
          </div>

          {autoOrderEnabled && (
            <div className="grid grid-cols-2 gap-4 pt-4 border-t">
              <div className="space-y-2">
                <Label htmlFor="safety-multiplier">Safety Stock Multiplier</Label>
                <Input
                  id="safety-multiplier"
                  type="number"
                  step="0.1"
                  min="1"
                  max="3"
                  value={reorderSettings.safetyStockMultiplier}
                  onChange={(e) => setReorderSettings(prev => ({
                    ...prev,
                    safetyStockMultiplier: parseFloat(e.target.value)
                  }))}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="lead-buffer">Lead Time Buffer (days)</Label>
                <Input
                  id="lead-buffer"
                  type="number"
                  min="0"
                  max="30"
                  value={reorderSettings.leadTimeBuffer}
                  onChange={(e) => setReorderSettings(prev => ({
                    ...prev,
                    leadTimeBuffer: parseInt(e.target.value)
                  }))}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="min-amount">Minimum Order Amount (₹)</Label>
                <Input
                  id="min-amount"
                  type="number"
                  min="0"
                  value={reorderSettings.minOrderAmount}
                  onChange={(e) => setReorderSettings(prev => ({
                    ...prev,
                    minOrderAmount: parseInt(e.target.value)
                  }))}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="auto-approve">Auto Approve Threshold (₹)</Label>
                <Input
                  id="auto-approve"
                  type="number"
                  min="0"
                  value={reorderSettings.autoApproveThreshold}
                  onChange={(e) => setReorderSettings(prev => ({
                    ...prev,
                    autoApproveThreshold: parseInt(e.target.value)
                  }))}
                />
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Low Stock Alerts */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-warning" />
            Items Requiring Reorder
          </CardTitle>
        </CardHeader>
        <CardContent>
          {lowStockItems.length > 0 ? (
            <div className="space-y-3">
              {lowStockItems.map((item) => (
                <div key={item.id} className="flex items-center justify-between p-3 border rounded-lg">
                  <div className="flex-1">
                    <p className="font-medium">{item.name}</p>
                    <p className="text-sm text-muted-foreground">
                      Current: {item.current_quantity} | Reorder Point: {item.reorder_point} | 
                      Suggested Qty: {calculateReorderQuantity(item)}
                    </p>
                  </div>
                  <Badge variant="destructive">Low Stock</Badge>
                </div>
              ))}
              <Button onClick={handleManualAutoOrder} className="w-full">
                <ShoppingCart className="h-4 w-4 mr-2" />
                Create Auto Orders Now
              </Button>
            </div>
          ) : (
            <div className="text-center py-8">
              <CheckCircle className="h-12 w-12 text-success mx-auto mb-4" />
              <p className="text-lg font-medium">All items are well stocked!</p>
              <p className="text-sm text-muted-foreground">No automatic reorders needed</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Auto Order History */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clock className="h-5 w-5 text-info" />
            Recent Auto Orders
          </CardTitle>
        </CardHeader>
        <CardContent>
          {autoOrderHistory.length > 0 ? (
            <div className="space-y-3">
              {autoOrderHistory.slice(0, 5).map((order) => (
                <div key={order.id} className="flex items-center justify-between p-3 border rounded-lg">
                  <div className="flex-1">
                    <p className="font-medium">{order.order_number}</p>
                    <p className="text-sm text-muted-foreground">
                      {order.suppliers?.name} • {order.order_items?.length} items
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {new Date(order.created_at).toLocaleString()}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold">₹{order.total_amount.toLocaleString()}</p>
                    <Badge variant={order.status === "pending" ? "default" : "secondary"}>
                      {order.status}
                    </Badge>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-8">
              <Package className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-sm text-muted-foreground">No automatic orders created yet</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Scheduled Orders */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Calendar className="h-5 w-5 text-primary" />
            Scheduled Orders
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8">
            <Settings className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-sm text-muted-foreground">Scheduled order functionality coming soon</p>
            <p className="text-xs text-muted-foreground mt-2">
              Set up recurring orders, seasonal inventory, and demand-based scheduling
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AutoOrderManager;



